//Used by Coblis: http://www.color-blindness.com/Coblis-color-blindness-simulator
// The original website posting the matrices has been taken down:
//http://www.colorjack.com/labs/colormatrix///
// RGB transform matrices generated by Michael of www.colorjack.com
//Which were created using code by Matthew Wickline and the
// Human-Computer Interaction Resource Network ( http://hcirn.com/ )
// The original matrices were 5x5, for full homogeneous coordinates of RGBA
//= They have been similified here to 3x3 matrices, because the additional 
// dimensions were simple identity.//// These are very inaccurate so consider other methods. See comments on this gist.var colorMats
// ref: https://gist.github.com/Lokno/df7c3bfdc9ad32558bb7
// final Map<String, List<double>> colorBlindnessMatrices = {
//   'Normal': [
//     1, 0, 0, 0, 0,
//     0, 1, 0, 0, 0,
//     0, 0, 1, 0, 0,
//     0, 0, 0, 1, 0,
//   ],
//   'Protanopia': [
//     0.567, 0.433, 0.000, 0, 0,
//     0.558, 0.442, 0.000, 0, 0,
//     0.000, 0.242, 0.758, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Protanomaly': [
//     0.817, 0.183, 0.000, 0, 0,
//     0.333, 0.667, 0.000, 0, 0,
//     0.000, 0.125, 0.875, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Deuteranopia': [
//     0.625, 0.375, 0.000, 0, 0,
//     0.700, 0.300, 0.000, 0, 0,
//     0.000, 0.300, 0.700, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Deuteranomaly': [
//     0.800, 0.200, 0.000, 0, 0,
//     0.258, 0.742, 0.000, 0, 0,
//     0.000, 0.142, 0.858, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Tritanopia': [
//     0.950, 0.050, 0.000, 0, 0,
//     0.000, 0.433, 0.567, 0, 0,
//     0.000, 0.475, 0.525, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Tritanomaly': [
//     0.967, 0.033, 0.000, 0, 0,
//     0.000, 0.733, 0.267, 0, 0,
//     0.000, 0.183, 0.817, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Achromatopsia': [
//     0.299, 0.587, 0.114, 0, 0,
//     0.299, 0.587, 0.114, 0, 0,
//     0.299, 0.587, 0.114, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
//   'Achromatomaly': [
//     0.618, 0.320, 0.062, 0, 0,
//     0.163, 0.775, 0.062, 0, 0,
//     0.163, 0.320, 0.516, 0, 0,
//     0,     0,     0,     1, 0,
//   ],
// };


class CVDFilters {
  static const List<double> protanopia = [
    0.567, 0.433, 0.000, 0, 0,
    0.558, 0.442, 0.000, 0, 0,
    0.000, 0.242, 0.758, 0, 0,
    0,     0,     0,     1, 0,
  ];

  static const List<double> deuteranopia = [
    0.625, 0.375, 0.000, 0, 0,
    0.700, 0.300, 0.000, 0, 0,
    0.000, 0.300, 0.700, 0, 0,
    0,     0,     0,     1, 0,
  ];

  static const List<double> tritanopia = [
    0.950, 0.050, 0.000, 0, 0,
    0.000, 0.433, 0.567, 0, 0,
    0.000, 0.475, 0.525, 0, 0,
    0,     0,     0,     1, 0,
  ];

  static const List<double> achromatopsia = [
    0.299, 0.587, 0.114, 0, 0,
    0.299, 0.587, 0.114, 0, 0,
    0.299, 0.587, 0.114, 0, 0,
    0,     0,     0,     1, 0,
  ];
  
  // Add the "Achromatomaly" you asked about too!
  static const List<double> achromatomaly = [
    0.618, 0.320, 0.062, 0, 0,
    0.163, 0.775, 0.062, 0, 0,
    0.163, 0.320, 0.516, 0, 0,
    0,     0,     0,     1, 0,
  ];
}